name: 기능 제안
description: 이런 기능이 있으면 좋겠어요
labels: ["제안"]
body:
  - type: textarea
    id: idea
    attributes:
      label: 어떤 기능인가요?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: 왜 필요한가요?
